---
title: "STAT 345 Final Project - Drunken Chessmaster"
author: "STAT 345 - Kirk Dahlke"
output: html_document
---

Expected Submission: You will generate a well-written R Markdown report that addresses the following prompts. This R Markdown report should source your analysis code and only display top-level, abstracted code _if/when appropriate_. Choices made during the analysis project should be described and justified in the report. The written report (knitted file) and your analysis code should be submitted to Canvas by Tuesday, May 13 at 6:45pm. 

Advice for getting started:

- Start a conversation chain with your group members. Email is a great place to start, but other options exist (texting, social media platforms, etc.). Set some reasonable expectations for how and when you plan to respond to conversations. It is likely going to be unacceptable to only respond once per week, for example, but also likely unacceptable to expect a response within the hour. Have an honest conversation with your group members about this issue.
- Start the project from a "top-down design" perspective. So, determine what the major steps of the process are, and determine what the inputs and outputs are for each of those steps (the output of step 1 will likely be the input for step 2, for example). This step is much like writing an outline for a paper before you start to write the paper itself, only much more valuable in a group setting. 
- Once you have a sense of the big picture (the outline), determine some "due dates" for each step of the process. Work backwards from the final submission date, giving yourselves time to work on each of the parts as needed. Given the top-down design, you should be able to "divide and conquer" -- working on parts of the project that depend on earlier steps.
- Decide how you plan to share code with each other. Using Git and GitHub is a really good choice here. If not, perhaps some form of shared directory online. In a worst-case scenario, email could also work. 
- Be prepared to give Dr. Baumann (at least) weekly updates on your progress. Some of this can be done via email, but discuss with your group about times you are each available to meet online as well (in an office-hour-like setting). Feel free to request meetings with Dr. Baumann to get help.

**General advice:** Get started early. If you wait to the last minute, it will not go well. For this project, you may find yourself spending a reasonable amount of time _searching_ for help.

1. _Plan Your Trip_ Imagine playing chess with only one piece by always selecting your next move at random from all possible legal moves. This is something a drunken chessmaster might do! Write a function to simulate this process for each of the "Back Row" pieces (rook, knight, bishop, queen, and king), starting at an arbitrary location and allowing for an arbitrary number of moves.

```{r}
install.packages("rchess")
library(rchess)
chss <- Chess$new()
chss$moves()
chss$clear()
chss$moves(verbose = TRUE)
chss$put("k", "w","e6")
plot(chss)
chss$moves()
chss$moves()[1:length(chss$moves())]
chss$move("Kd6#")
sample(1:length(chss$moves()), 1)
chss$put("k", "b", "d6")
```

2. _Popular Destinations_ Use your functions from part 1 to simulate 1000 moves, starting from several different positions. Create a data visualization of the resulting moves (or alternatively, of the resulting positions).

3. _Vacation Duration_ How many moves does it take for each piece to return where it started? Does it matter where you start? Characterize these distributions.

4. _Visit Some Friends_ Consider two drunken chessmasters playing against each other. They both start with a king and a queen, in the traditional starting positions. They each will take turns making moves at random from all possible legal moves. The players are allowed to "attack" the other player's pieces, and the game stops when a player attacks the other player's King. Simulate this process. (Since these chessmasters are presumably drunk, you may ignore the conditions and rules that place a King into "check".)

5. _Share the Pictures_ Where do the games in part 4 typically end?  How long does it take for these games to end? Create data visualizations to summarize these drunken games.




